### PR TITLE
Inven PR to track changes

### PR DESCRIPTION
**Pull request by dpastoor**
Dialog in the PR probably more relevant than issue

### CODE REVIEW

**Comment by dpastoor** [comment]
Sweet! Already looks great.

I wonder for the need syntax if we could consider leveraging dplyr select-style implementation

```
data_set(..., need=vars(CL:V2))
data_set(..., need=vars(everything()))

idata_set(..., need=vars(starts_with("E"))) # if every eta prefaced with E maybe
```

**Comment by kylebmetrum** [comment]
That's a good idea to leverage dplyr select stuff.  That sort of thing could really make or break this.  If specifying `need` is clumsy or inflexible, this won't work well.

**Comment by dpastoor** [comment]
so I'm digging around, and at least in the new version of dplyr, they are exposing a lot of the select machinery

https://github.com/tidyverse/dplyr/blob/85ad81813da7eef90b89d7d1b76c3edb807ff217/R/select-vars.R

``` r
library(dplyr)


names(Theoph)
#> [1] "Subject" "Wt"      "Dose"    "Time"    "conc"

select_vars(names(Theoph), Dose:conc)
#>   Dose   Time   conc 
#> "Dose" "Time" "conc"

select_vars(names(Theoph), -conc, -Dose)
#>   Subject        Wt      Time 
#> "Subject"      "Wt"    "Time"
```

**Comment by dpastoor** [comment]
so....

``` r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union


## we'd pull this internally from the mrgmod
## so hard coding to fake that
.data <- names(Theoph)

need <- function(...){
  select_vars(.data, ...)
}
  
need(everything())
#>   Subject        Wt      Dose      Time      conc 
#> "Subject"      "Wt"    "Dose"    "Time"    "conc"

need(Wt:conc)
#>     Wt   Dose   Time   conc 
#>   "Wt" "Dose" "Time" "conc"
```

**Comment by kylebmetrum** [comment]
`select_vars_` is exposed in `0.5.0`.  This works fine for the `inventory` function where we can just take the dots and required parameters for that object.  `data_set` etc are more complicated functions.  So would it be:

```
mod %>% data_set(data, need=vars(CL:V2,KM,KA)) %>% 
```
or whatever?

**Comment by kylebmetrum** [comment]
This is sweet.

```r
> code <- '$PARAM CL = 1 , V2 = 3, KA = 4, VM = 5'
> 
> mod <- mcode_cache("tst", code)
Loading model from cache.
> 
> idat <- data_frame(CL=1,V2=3,KA=4,VM=10)
> 
> inventory(mod,idat, everything())
Found all required parameters
```

**Comment by kylebmetrum** [comment]
```r
> code <- '$PARAM CL = 1 , V2 = 3, KA = 4, VM = 5'
> inventory(mod,idat,CL:KA)
object is missing these parameters
 - V2
```

**Comment by dpastoor** [comment]
exactly - do note though that select_vars_ (and every `_` function) is deprecated in 0.6.0.  I'm trying to think if there is a (reasonably) elegant way of supporting both 0.5 and 0.6 without knowingly using a soon-to-be-deprecated function.

Regardless - this feels cleaner - really liking it!

**Comment by kylebmetrum** [comment]
I see.  Thanks for clarifying that ... and for suggesting the select stuff.  I like this a lot.  Definitely going to keep heading down this path.

**Comment by kylebmetrum** [comment]
This is on the same PR unfortunately.  Based on @dpastoor suggestion in #218, changing `mutate_each` to `mutate_at` only if using the new `dplyr.  There is also conditional import (`mutate_each` or `mutate_at`).

@dpastoor should we support both `dplyr` versions and then just require `dplyr >= 0.6.0` at some point?

I haven't really gotten into `0.6.0` or anything ... there may be other gremlins in there.  But as of now, we're passing tests and check.

**Comment by kylebmetrum** [comment]
Verifying that everything still works after reverting to `dplyr 0.5.0`.

**Comment by dpastoor** [comment]
@kylebmetrum I am not sure regarding dplyr 0.5 + 0.6 support atm. I can definitely address this in the next couple weeks as I can dig into rlang vs lazyeval. The main thing that I am not sure of is given the new syntax with the `!!` to indicate that it is a reference to a variable vs a named value in the data, how will that support work for packages that don't understand rlang-based syntax. 

My thoughts are that it should be possible to support both, especially in the short term. The worst case scenario is once rlang is on CRAN that can be the standardized external api that mrgsolve uses, which would just directly pass through to dplyr 0.6, but internally could wrap the dplyr 0.5 syntax as well.

Let me check back in around the 15-20th and I can give some more conclusive thoughts. This is something that I am generally wondering about beyond mrgsolve so it definitely needs to be addressed.

**Pull request merged**
