### PR TITLE
refactor carry out for nocb

### PR DESCRIPTION
**Pull request by kylebaron**
See #753 

- this re-factors carry out so that it takes the actual row value when possible and the next row otherwise
- when `nocb = FALSE` we carry forward

### CODE REVIEW

**Comment by kylebaron** [comment]
``` r
library(mrgsolve)
#> 
#> Attaching package: 'mrgsolve'
#> The following object is masked from 'package:stats':
#> 
#>     filter
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
code <- "
$PARAM CL0 = .1, V = 10, COV = 100
$CMT CENT
$PKMODEL ncmt = 1
$TABLE
double DV  = CENT / V  ;
$MAIN
double CL = CL0 / V * COV ;
$CAPTURE DV, CL, COV2 = COV
"
modelobsaug <- mread("testobsaug",code = code)
#> Building testobsaug ...
#> done.

dat1 <- data.frame(
  ID = 1, 
  time = c(0, 12.1, 24),
  evid = c(1, 0, 0),
  amt = c(100, 0, 0), 
  cmt = 1, 
  COV = c(100, 100, 50)
)

dat2 <- mutate(dat1, ID = 2)
data <- bind_rows(dat1,dat2)

data
#>   ID time evid amt cmt COV
#> 1  1  0.0    1 100   1 100
#> 2  1 12.1    0   0   1 100
#> 3  1 24.0    0   0   1  50
#> 4  2  0.0    1 100   1 100
#> 5  2 12.1    0   0   1 100
#> 6  2 24.0    0   0   1  50

modelobsaug %>%
  data_set(data) %>%
  mrgsim_df(carry_out = "COV")
#>   ID time COV      CENT        DV  CL COV2
#> 1  1  0.0 100 100.00000 10.000000 1.0  100
#> 2  1 12.1 100  29.81973  2.981973 1.0  100
#> 3  1 24.0  50  16.44745  1.644745 0.5   50
#> 4  2  0.0 100 100.00000 10.000000 1.0  100
#> 5  2 12.1 100  29.81973  2.981973 1.0  100
#> 6  2 24.0  50  16.44745  1.644745 0.5   50

modelobsaug %>%
  obsaug() %>% 
  data_set(data) %>%
  mrgsim_df(carry_out = "COV") 
#>    ID time COV      CENT        DV  CL COV2
#> 1   1  0.0 100   0.00000  0.000000 1.0  100
#> 2   1  0.0 100 100.00000 10.000000 1.0  100
#> 3   1  1.0 100  90.48374  9.048374 1.0  100
#> 4   1  2.0 100  81.87308  8.187308 1.0  100
#> 5   1  3.0 100  74.08182  7.408182 1.0  100
#> 6   1  4.0 100  67.03200  6.703200 1.0  100
#> 7   1  5.0 100  60.65307  6.065307 1.0  100
#> 8   1  6.0 100  54.88116  5.488116 1.0  100
#> 9   1  7.0 100  49.65853  4.965853 1.0  100
#> 10  1  8.0 100  44.93290  4.493290 1.0  100
#> 11  1  9.0 100  40.65697  4.065697 1.0  100
#> 12  1 10.0 100  36.78794  3.678794 1.0  100
#> 13  1 11.0 100  33.28711  3.328711 1.0  100
#> 14  1 12.0 100  30.11942  3.011942 1.0  100
#> 15  1 12.1 100  29.81973  2.981973 1.0  100
#> 16  1 13.0  50  28.50758  2.850758 0.5   50
#> 17  1 14.0  50  27.11725  2.711725 0.5   50
#> 18  1 15.0  50  25.79473  2.579473 0.5   50
#> 19  1 16.0  50  24.53671  2.453671 0.5   50
#> 20  1 17.0  50  23.34004  2.334004 0.5   50
#> 21  1 18.0  50  22.20173  2.220173 0.5   50
#> 22  1 19.0  50  21.11894  2.111894 0.5   50
#> 23  1 20.0  50  20.08896  2.008896 0.5   50
#> 24  1 21.0  50  19.10921  1.910921 0.5   50
#> 25  1 22.0  50  18.17724  1.817724 0.5   50
#> 26  1 23.0  50  17.29072  1.729072 0.5   50
#> 27  1 24.0  50  16.44745  1.644745 0.5   50
#> 28  1 24.0  50  16.44745  1.644745 0.5   50
#> 29  2  0.0 100   0.00000  0.000000 1.0  100
#> 30  2  0.0 100 100.00000 10.000000 1.0  100
#> 31  2  1.0 100  90.48374  9.048374 1.0  100
#> 32  2  2.0 100  81.87308  8.187308 1.0  100
#> 33  2  3.0 100  74.08182  7.408182 1.0  100
#> 34  2  4.0 100  67.03200  6.703200 1.0  100
#> 35  2  5.0 100  60.65307  6.065307 1.0  100
#> 36  2  6.0 100  54.88116  5.488116 1.0  100
#> 37  2  7.0 100  49.65853  4.965853 1.0  100
#> 38  2  8.0 100  44.93290  4.493290 1.0  100
#> 39  2  9.0 100  40.65697  4.065697 1.0  100
#> 40  2 10.0 100  36.78794  3.678794 1.0  100
#> 41  2 11.0 100  33.28711  3.328711 1.0  100
#> 42  2 12.0 100  30.11942  3.011942 1.0  100
#> 43  2 12.1 100  29.81973  2.981973 1.0  100
#> 44  2 13.0  50  28.50758  2.850758 0.5   50
#> 45  2 14.0  50  27.11725  2.711725 0.5   50
#> 46  2 15.0  50  25.79473  2.579473 0.5   50
#> 47  2 16.0  50  24.53671  2.453671 0.5   50
#> 48  2 17.0  50  23.34004  2.334004 0.5   50
#> 49  2 18.0  50  22.20173  2.220173 0.5   50
#> 50  2 19.0  50  21.11894  2.111894 0.5   50
#> 51  2 20.0  50  20.08896  2.008896 0.5   50
#> 52  2 21.0  50  19.10921  1.910921 0.5   50
#> 53  2 22.0  50  18.17724  1.817724 0.5   50
#> 54  2 23.0  50  17.29072  1.729072 0.5   50
#> 55  2 24.0  50  16.44745  1.644745 0.5   50
#> 56  2 24.0  50  16.44745  1.644745 0.5   50
```

<sup>Created on 2020-11-05 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Review by FelicienLL — COMMENTED** [review]
I do not know the source code nor cpp language enough to review the commit itself. But obviously, judging by the test, lgtm.

**Comment by kylebaron** [comment]
reprex that it works with `nocb=FALSE`
``` r
library(mrgsolve)
#> 
#> Attaching package: 'mrgsolve'
#> The following object is masked from 'package:stats':
#> 
#>     filter
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
code <- "
$PARAM CL0 = .1, V = 10, COV = 100
$CMT CENT
$PKMODEL ncmt = 1
$TABLE
double DV  = CENT / V  ;
$MAIN
double CL = CL0 / V * COV ;
$CAPTURE DV, CL, COV2 = COV
"
modelobsaug <- mcode("testobsaug",code = code)
#> Building testobsaug ...
#> done.

dat1 <- data.frame(
  ID = 1, 
  time = c(0, 12.1, 24),
  evid = c(1, 0, 0),
  amt = c(100, 0, 0), 
  cmt = 1, 
  COV = c(100, 100, 50)
)

dat2 <- mutate(dat1, ID = 2)
data <- bind_rows(dat1,dat2)

data
#>   ID time evid amt cmt COV
#> 1  1  0.0    1 100   1 100
#> 2  1 12.1    0   0   1 100
#> 3  1 24.0    0   0   1  50
#> 4  2  0.0    1 100   1 100
#> 5  2 12.1    0   0   1 100
#> 6  2 24.0    0   0   1  50


modelobsaug %>%
  obsaug() %>% 
  data_set(data) %>%
  mrgsim_df(carry_out = "COV", nocb = FALSE, delta = 4) 
#>    ID time COV       CENT         DV CL COV2
#> 1   1  0.0 100   0.000000  0.0000000  1  100
#> 2   1  0.0 100 100.000000 10.0000000  1  100
#> 3   1  4.0 100  67.032005  6.7032005  1  100
#> 4   1  8.0 100  44.932896  4.4932896  1  100
#> 5   1 12.0 100  30.119421  3.0119421  1  100
#> 6   1 12.1 100  29.819728  2.9819728  1  100
#> 7   1 16.0 100  20.189652  2.0189652  1  100
#> 8   1 20.0 100  13.533528  1.3533528  1  100
#> 9   1 24.0 100   9.071795  0.9071795  1  100
#> 10  1 24.0  50   9.071795  0.9071795  1   50
#> 11  2  0.0 100   0.000000  0.0000000  1  100
#> 12  2  0.0 100 100.000000 10.0000000  1  100
#> 13  2  4.0 100  67.032005  6.7032005  1  100
#> 14  2  8.0 100  44.932896  4.4932896  1  100
#> 15  2 12.0 100  30.119421  3.0119421  1  100
#> 16  2 12.1 100  29.819728  2.9819728  1  100
#> 17  2 16.0 100  20.189652  2.0189652  1  100
#> 18  2 20.0 100  13.533528  1.3533528  1  100
#> 19  2 24.0 100   9.071795  0.9071795  1  100
#> 20  2 24.0  50   9.071795  0.9071795  1   50
```

<sup>Created on 2020-11-06 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by kylebaron** [comment]
@FelicienLL would you mind sending me an email at the address in my github profile? 
I'd like to touch base with you if you don't mind.

**Review by timwaterhouse — APPROVED** [review]
Looks good

**Pull request merged**
