### PR TITLE
Feature collapse OMEGA or SIGMA matrix lists

### PR DESCRIPTION
**Pull request by kylebaron**
# Summary

See #897 and #894 

- Export `collapse_omega`, `collapse_sigma` and `collapse_matrix`
- Add `range` argument to limit which matrices are collapsed
  - `range` must be numeric vector, length 2
  - `range[2]` can be `NA` and we'll take it to be the length of the matlist
- Add `name` argument to rename the collapsed chunk

# Examples

``` r
library(mrgsolve)
#> 
#> Attaching package: 'mrgsolve'
#> The following object is masked from 'package:stats':
#> 
#>     filter
code0 <- "
$OMEGA @annotated @name et
ET1 : 1 : CL
$OMEGA 
2 
@labels a
$OMEGA 1 2 3
$OMEGA @name last @labels v w
4 5
$CAPTURE ET1 ETA(2)
"
mod <- mcode("omega", code0)
#> Building omega ...
#> done.
x <- omat(mod)
collapse_omega(mod) %>% revar()
#> $omega
#> $...
#>       [,1] [,2] [,3] [,4] [,5] [,6] [,7]
#> ET1:     1    0    0    0    0    0    0
#> a:       0    2    0    0    0    0    0
#> 3:       0    0    1    0    0    0    0
#> 4:       0    0    0    2    0    0    0
#> 5:       0    0    0    0    3    0    0
#> v:       0    0    0    0    0    4    0
#> w:       0    0    0    0    0    0    5
#> 
#> 
#> $sigma
#> No matrices found
collapse_omega(mod, c(2,3), name = "NewMatrix") %>% revar()
#> $omega
#> $et
#>       [,1]
#> ET1:     1
#> 
#> $NewMatrix
#>     [,1] [,2] [,3] [,4]
#> a:     2    0    0    0
#> 3:     0    1    0    0
#> 4:     0    0    2    0
#> 5:     0    0    0    3
#> 
#> $last
#>     [,1] [,2]
#> v:     4    0
#> w:     0    5
#> 
#> 
#> $sigma
#> No matrices found
collapse_matrix(x, c(1,2), name = "blah") 
#> $blah
#>       [,1] [,2]
#> ET1:     1    0
#> a:       0    2
#> 
#> $...
#>     [,1] [,2] [,3]
#> 3:     1    0    0
#> 4:     0    2    0
#> 5:     0    0    3
#> 
#> $last
#>     [,1] [,2]
#> v:     4    0
#> w:     0    5
```

<sup>Created on 2021-12-16 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

### CODE REVIEW

**Comment by kylebaron** [comment]
# Examples

``` r
library(mrgsolve)
#> 
#> Attaching package: 'mrgsolve'
#> The following object is masked from 'package:stats':
#> 
#>     filter
code0 <- "
$OMEGA @annotated @name et
ET1 : 1 : CL
$OMEGA 
2 
@labels a
$OMEGA 1 2 3
$OMEGA @name last @labels v w
4 5
$CAPTURE ET1 ETA(2)
"
mod <- mcode("omega", code0)
#> Building omega ...
#> done.
x <- omat(mod)
collapse_omega(mod) %>% revar()
#> $omega
#> $...
#>       [,1] [,2] [,3] [,4] [,5] [,6] [,7]
#> ET1:     1    0    0    0    0    0    0
#> a:       0    2    0    0    0    0    0
#> 3:       0    0    1    0    0    0    0
#> 4:       0    0    0    2    0    0    0
#> 5:       0    0    0    0    3    0    0
#> v:       0    0    0    0    0    4    0
#> w:       0    0    0    0    0    0    5
#> 
#> 
#> $sigma
#> No matrices found
collapse_omega(mod, c(2,3), name = "NewMatrix") %>% revar()
#> $omega
#> $et
#>       [,1]
#> ET1:     1
#> 
#> $NewMatrix
#>     [,1] [,2] [,3] [,4]
#> a:     2    0    0    0
#> 3:     0    1    0    0
#> 4:     0    0    2    0
#> 5:     0    0    0    3
#> 
#> $last
#>     [,1] [,2]
#> v:     4    0
#> w:     0    5
#> 
#> 
#> $sigma
#> No matrices found
collapse_matrix(x, c(1,2), name = "blah") 
#> $blah
#>       [,1] [,2]
#> ET1:     1    0
#> a:       0    2
#> 
#> $...
#>     [,1] [,2] [,3]
#> 3:     1    0    0
#> 4:     0    2    0
#> 5:     0    0    3
#> 
#> $last
#>     [,1] [,2]
#> v:     4    0
#> w:     0    5
```

<sup>Created on 2021-12-16 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Review by timwaterhouse — COMMENTED** [review]
I'm just looking at tests and documentation and trying some examples, but this looks good.

**Comment by kylebaron** [comment]
Thanks, @timwaterhouse ; let me know if anything needs updating.

**Comment by timwaterhouse** [comment]
@kylebaron Not that I can see, no. Do you need an explicit approval on this? Happy to do so.

**Comment by kylebaron** [comment]
Thanks, @timwaterhouse ; yes, looking for review / approval (if appropriate) to merge.

**Review by timwaterhouse — APPROVED** [review]

**Pull request merged**
