### PR TITLE
Changes in 2017

### PR DESCRIPTION
**Pull request by kylebmetrum**
As usual, a variety of stuff.

### CODE REVIEW

**Comment by vjd** [comment]
Just went through the details and realized that there are so many incredible features since I last worked with mrgsolve about 4 months ago. This is a great beginning to 2017!

**Comment by kylebmetrum** [comment]
I tweeted out a bunch of stuff today and making serious effort to get this documented. @vjd @dpastoor

**Comment by vjd** [comment]
I am actually testing the $ENV since this am.. will keep you posted!

**Comment by mrgsolve** [comment]
Great!  Feedback please ... that `covset` stuff has been about 10 different things.  I'm finally feeling ok about how it looks and the implementation too. I'm not hugely invested in doing all of this "inside" the model, so tried to allow user to decide what gets embedded into the model and what doesn't.  Maybe a little more work that way, but hopefully the flexibility pays off.  And just settled on the "form" of the thing ... probably lots to do in terms of error checking etc. It would also be nice to add some expressions or formulae that just `mutate` columns in the data set.

**Pull request merged**
